/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MedicalPassRouteImport } from './routes/medical-pass'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as FirstAidRouteImport } from './routes/first-aid'
import { Route as EmergencyRouteImport } from './routes/emergency'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicalPassRoute = MedicalPassRouteImport.update({
  id: '/medical-pass',
  path: '/medical-pass',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const FirstAidRoute = FirstAidRouteImport.update({
  id: '/first-aid',
  path: '/first-aid',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRoute = EmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/emergency': typeof EmergencyRoute
  '/first-aid': typeof FirstAidRoute
  '/history': typeof HistoryRoute
  '/medical-pass': typeof MedicalPassRoute
  '/profile': typeof ProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/emergency': typeof EmergencyRoute
  '/first-aid': typeof FirstAidRoute
  '/history': typeof HistoryRoute
  '/medical-pass': typeof MedicalPassRoute
  '/profile': typeof ProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/emergency': typeof EmergencyRoute
  '/first-aid': typeof FirstAidRoute
  '/history': typeof HistoryRoute
  '/medical-pass': typeof MedicalPassRoute
  '/profile': typeof ProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/emergency'
    | '/first-aid'
    | '/history'
    | '/medical-pass'
    | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/emergency'
    | '/first-aid'
    | '/history'
    | '/medical-pass'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/emergency'
    | '/first-aid'
    | '/history'
    | '/medical-pass'
    | '/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  EmergencyRoute: typeof EmergencyRoute
  FirstAidRoute: typeof FirstAidRoute
  HistoryRoute: typeof HistoryRoute
  MedicalPassRoute: typeof MedicalPassRoute
  ProfileRoute: typeof ProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medical-pass': {
      id: '/medical-pass'
      path: '/medical-pass'
      fullPath: '/medical-pass'
      preLoaderRoute: typeof MedicalPassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/first-aid': {
      id: '/first-aid'
      path: '/first-aid'
      fullPath: '/first-aid'
      preLoaderRoute: typeof FirstAidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency': {
      id: '/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof EmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  EmergencyRoute: EmergencyRoute,
  FirstAidRoute: FirstAidRoute,
  HistoryRoute: HistoryRoute,
  MedicalPassRoute: MedicalPassRoute,
  ProfileRoute: ProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
